### PR TITLE
Docs/old wiki

### PR DESCRIPTION
**Pull request by xeTaiz**
Ports remaining parts from the GitHub wiki to our new docs.
As I mentioned in [this issue](https://github.com/inviwo/inviwo/issues/86), this should be most of the remaining things. Links were adapted.

### CODE REVIEW

**Comment by petersteneteg** [comment]
Nice! then we can delete the wiki?

**Comment by xeTaiz** [comment]
I think so.
There is the "How to write a bug report" thing remaining, that should be solved with the gh issue template anyways.
There's also a few Coding Guidelines. Maybe we should include those in some kind of Contributing page? 
Afaik we don't have such a page yet?

**Comment by petersteneteg** [comment]
Yes, that would be reasonable I think.

**Comment by xeTaiz** [comment]
there it is, plese have a quick look. I think we can delete the wiki then

**Review by petersteneteg — APPROVED** [review]
Think this is ok for now, need to go through it all in place and see what should be updated

**Pull request merged**
